### PR TITLE
feature/BGT-376: add the __type attribute for AssetProperty

### PR DESCRIPTION
**Pull request by hcrocker**

### CODE REVIEW

**Comment by servicemesh-autobuild** [comment]
:x: Build failed

http://172.22.12.115:8080/job/csc-agility-platform-sdk-prb/268/

**Comment by hcrocker** [comment]
retest

**Comment by servicemesh-autobuild** [comment]
:x: Build failed

http://172.22.12.115:8080/job/csc-agility-platform-sdk-prb/269/

**Comment by servicemesh-autobuild** [comment]
:white_check_mark: Build was successful :tada:


http://172.22.12.115:8080/job/csc-agility-platform-sdk-prb/270/

**Comment by servicemesh-autobuild** [comment]
:white_check_mark: Build was successful :tada:


http://172.22.12.115:8080/job/csc-agility-platform-sdk-prb/271/

**Pull request merged**
